BEGIN;

CREATE TABLE IF NOT EXISTS public.assets_local (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code TEXT NOT NULL,
    location   TEXT,
    status     TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_assets_local_code ON public.assets_local(asset_code);
CREATE INDEX IF NOT EXISTS ix_assets_local_created_at ON public.assets_local(created_at);

CREATE TABLE IF NOT EXISTS public.measurement_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL REFERENCES public.assets_local(id) ON DELETE CASCADE,
    label    TEXT   NOT NULL,
    CONSTRAINT uq_points_asset_label UNIQUE(asset_id, label)
);

CREATE TABLE IF NOT EXISTS public.measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_id  BIGINT NOT NULL REFERENCES public.measurement_points(id) ON DELETE CASCADE,
    ts        TIMESTAMPTZ NOT NULL,
    thickness NUMERIC(10,3) NOT NULL CHECK (thickness > 0),
    note      TEXT
);
CREATE INDEX IF NOT EXISTS ix_measurements_point_ts ON public.measurements(point_id, ts);

CREATE TABLE IF NOT EXISTS public.local_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type   TEXT,
    payload_json JSONB,
    created_at   TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_local_events_created_at ON public.local_events(created_at);

COMMIT;
