BEGIN;

-- 1) assets_global
CREATE TABLE IF NOT EXISTS public.assets_global (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code TEXT NOT NULL UNIQUE,
    name TEXT,
    type TEXT,
    plant_code TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_assets_global_created_at ON public.assets_global(created_at);

-- 2) risk_policies
CREATE TABLE IF NOT EXISTS public.risk_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    threshold_low  NUMERIC,
    threshold_med  NUMERIC,
    threshold_high NUMERIC
);

-- 3) analytics_cr
CREATE TABLE IF NOT EXISTS public.analytics_cr (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code TEXT NOT NULL,
    prev_thk   NUMERIC,
    prev_date  TIMESTAMPTZ,
    last_thk   NUMERIC,
    last_date  TIMESTAMPTZ,
    cr         NUMERIC,
    updated_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT fk_analytics_cr_asset
        FOREIGN KEY (asset_code) REFERENCES public.assets_global(asset_code) ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_analytics_cr_asset_code ON public.analytics_cr(asset_code);
CREATE INDEX IF NOT EXISTS ix_analytics_cr_updated_at ON public.analytics_cr(updated_at);

-- 4) measurement_batches (прямая вставка через FDW с заводов, без очереди)
CREATE TABLE IF NOT EXISTS public.measurement_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_plant TEXT NOT NULL,
    asset_code   TEXT NOT NULL,
    prev_thk     NUMERIC,
    prev_date    TIMESTAMPTZ,
    last_thk     NUMERIC(10,3) NOT NULL CHECK (last_thk > 0),
    last_date    TIMESTAMPTZ NOT NULL,
    last_label   TEXT,
    last_note    TEXT,
    created_at   TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT fk_measurement_batches_asset
        FOREIGN KEY (asset_code) REFERENCES public.assets_global(asset_code) ON UPDATE CASCADE,
    CONSTRAINT chk_measurement_batches_asset_code
        CHECK (NULLIF(trim(asset_code), '') IS NOT NULL),
    CONSTRAINT chk_measurement_batches_order
        CHECK (prev_date IS NULL OR prev_date <= last_date),
    CONSTRAINT chk_measurement_batches_thk
        CHECK (prev_thk IS NULL OR prev_thk >= last_thk)
);
CREATE INDEX IF NOT EXISTS ix_measurement_batches_created_at ON public.measurement_batches(created_at);
CREATE INDEX IF NOT EXISTS ix_measurement_batches_asset_code ON public.measurement_batches(asset_code);
CREATE INDEX IF NOT EXISTS ix_measurement_batches_source_plant ON public.measurement_batches(source_plant);

ALTER TABLE IF EXISTS public.measurement_batches
  ADD COLUMN IF NOT EXISTS last_label TEXT;
ALTER TABLE IF EXISTS public.measurement_batches
  ADD COLUMN IF NOT EXISTS last_note TEXT;

-- 5) asset cleanup requests (from plants via FDW)
CREATE TABLE IF NOT EXISTS public.asset_cleanup_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_plant TEXT NOT NULL,
    asset_code   TEXT NOT NULL,
    requested_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_asset_cleanup_requests_requested_at ON public.asset_cleanup_requests(requested_at);

-- Upgrade path: если таблица была создана в старой версии без identity/default на id,
-- вставки через FDW будут падать с "null value in column id".
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.table_name = 'measurement_batches'
      AND c.column_name = 'id'
      AND c.udt_name = 'int8'
      AND c.is_identity = 'NO'
      AND c.column_default IS NULL
  ) THEN
    ALTER TABLE public.measurement_batches
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END$$;

COMMIT;
