BEGIN;

-- 1) assets_global
CREATE TABLE IF NOT EXISTS public.assets_global (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code TEXT NOT NULL UNIQUE,
    name TEXT,
    type TEXT,
    plant_code TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_assets_global_created_at ON public.assets_global(created_at);

-- 2) risk_policies
CREATE TABLE IF NOT EXISTS public.risk_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    threshold_low  NUMERIC,
    threshold_med  NUMERIC,
    threshold_high NUMERIC
);

-- 3) analytics_cr
CREATE TABLE IF NOT EXISTS public.analytics_cr (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code TEXT NOT NULL,
    prev_thk   NUMERIC,
    prev_date  TIMESTAMPTZ,
    last_thk   NUMERIC,
    last_date  TIMESTAMPTZ,
    cr         NUMERIC,
    updated_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT fk_analytics_cr_asset
        FOREIGN KEY (asset_code) REFERENCES public.assets_global(asset_code) ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_analytics_cr_asset_code ON public.analytics_cr(asset_code);
CREATE INDEX IF NOT EXISTS ix_analytics_cr_updated_at ON public.analytics_cr(updated_at);

-- 4) events_inbox
CREATE TABLE IF NOT EXISTS public.events_inbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type   TEXT NOT NULL CHECK (event_type = 'HC_MEASUREMENT_BATCH'),
    source_plant TEXT,
    payload_json JSONB NOT NULL,
    created_at   TIMESTAMPTZ DEFAULT now(),
    processed_at TIMESTAMPTZ NULL
);
CREATE INDEX IF NOT EXISTS ix_events_inbox_created_at ON public.events_inbox(created_at);
CREATE INDEX IF NOT EXISTS ix_events_inbox_processed_null ON public.events_inbox(processed_at) WHERE processed_at IS NULL;

-- enforce default/constraints even on existing deployments
ALTER TABLE public.events_inbox ALTER COLUMN event_type SET DEFAULT 'HC_MEASUREMENT_BATCH';
UPDATE public.events_inbox SET event_type = 'HC_MEASUREMENT_BATCH' WHERE event_type IS NULL;

DO $$
BEGIN
  BEGIN
    ALTER TABLE public.events_inbox ALTER COLUMN event_type SET NOT NULL;
  EXCEPTION WHEN others THEN
    -- ignore if already enforced
    NULL;
  END;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chk_events_inbox_type'
      AND conrelid = 'public.events_inbox'::regclass
  ) THEN
    ALTER TABLE public.events_inbox
      ADD CONSTRAINT chk_events_inbox_type CHECK (event_type = 'HC_MEASUREMENT_BATCH') NOT VALID;
  END IF;
END$$;

COMMIT;
